name: Print PR Diff Workflow
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  print-diff:
    runs-on: ubuntu-latest
    steps:
      - name: Print PR Diff
        uses: devnjw/code-review-action@v0.2
