name: Print PR Diff Workflow
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  print-diff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Print PR Diff
        uses: devnjw/code-review-action@v0.3
        with:
          fetch-depth: 0
